cargo-features = ["edition"]

[package]
name = "runtime"
version = "0.1.0"
edition = "2018"
authors = ["Ryan Cumming <etaoins@gmail.com>"]

[lib]
name = "runtime"
path = "lib.rs"
crate-type = ["lib", "dylib"]
