[package]
name = "runtime-syntax"
version = "0.1.0"
edition = "2018"
authors = ["Ryan Cumming <etaoins@gmail.com>"]

[lib]
path = "lib.rs"
crate-type = ["lib", "dylib"]

[dependencies]
syntax = { path = "../syntax" }
runtime = { path = "../runtime" }
