cached-ecr-build-env: &cached-ecr-build-env
  plugins:
    - seek-oss/docker-ecr-cache#v1.9.0:
        target: build-env
        cache-on:
          - Cargo.lock
    - docker#v3.8.0

docker-ghcr-login: &docker-ghcr-login
  docker-login#v2.0.1:
    server: ghcr.io
    username: etaoins
    password-env: CR_PAT

steps:
  - label: ':muscle: Test ARM64'
    agents: { queue: arm64 }
    command:
      - ./.buildkite/build-and-test.sh

      - "echo '--- :sleuth_or_spy: Checking release'"
      - RUSTFLAGS="-Copt-level=0" cargo check --release
    <<: *cached-ecr-build-env

  - label: ':ubuntu: Test AMD64'
    agents: { queue: amd64 }
    command:
      - ./.buildkite/build-and-test.sh
    <<: *cached-ecr-build-env

  - label: ':fedora: Test LLVM assert'
    branches: '!master'
    agents: { queue: arm64 }
    command:
      - "echo '--- :prettier: Checking rustfmt'"
      - cargo fmt -- --check

      - ./.buildkite/build-and-test.sh
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          dockerfile: ./.buildkite/llvm-assert.Dockerfile
      - docker#v3.8.0

  - label: ':typescript: Test VS Code extension'
    agents: { queue: amd64 }
    command:
      - ./.buildkite/vscode-extension-tests.sh
    plugins:
      - seek-oss/docker-ecr-cache#v1.9.0:
          dockerfile: ./editors/code/Dockerfile
          ecr-name: build-cache/arret/vscode-extension
          cache-on:
            - ./editors/code/yarn.lock
            - ./editors/code/src/test/vsCodeVersion.ts
      - docker#v3.8.0:
          volumes:
            - '/workdir/editors/code/node_modules'
            - '/workdir/editors/code/.vscode-test'

  - wait

  - label: ':mechanical_arm: Push ARM64 REPL image'
    key: 'push-arm64-repl-image'
    branches: 'master'
    agents: { queue: arm64 }
    plugins:
      - *docker-ghcr-login
      - docker-compose#v3.7.0:
          push:
            - repl:ghcr.io/etaoins/arret-repl-arm64
          env:
            - BUILDKITE_COMMIT

  - label: ':rocket: Push AMD64 REPL image'
    key: 'push-amd64-repl-image'
    branches: 'master'
    agents: { queue: amd64 }
    plugins:
      - *docker-ghcr-login
      - docker-compose#v3.7.0:
          push:
            - repl:ghcr.io/etaoins/arret-repl-amd64
          env:
            - BUILDKITE_COMMIT

  - label: ':docker: Update multiarch manifest'
    branches: 'master'
    agents: { queue: arm64 }
    depends_on:
      - 'push-amd64-repl-image'
      - 'push-arm64-repl-image'
    command:
      - ./.buildkite/update-multiarch-manifest.sh
    plugins:
      - *docker-ghcr-login

  - label: ':rust: Check (Rust Beta)'
    branches: 'master'
    agents: { queue: arm64 }
    command:
      - "echo '--- :rust: Installing Rust beta'"
      - rustup default beta

      - "echo '--- :male-detective: Checking debug'"
      - cargo check

      - "echo '--- :female-detective: Checking release'"
      - RUSTFLAGS="-Copt-level=0" cargo check --release
    <<: *cached-ecr-build-env

  - label: ':books: Update Rustdoc'
    branches: 'master'
    agents: { queue: arm64 }
    command:
      - "echo '--- :book: Building rustdoc'"
      - cargo doc --no-deps

      - "echo '--- :rust: Installing awscli'"
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get -y install awscli

      - ./.buildkite/sync-rustdoc.sh
    <<: *cached-ecr-build-env
    concurrency_group: 'update-rustdoc'
    concurrency: 1
