steps:
  - label: ":docker: Build & Test"
    command:
      - /bin/bash -c "cargo build && cargo test && ./.buildkite/cross-i686.sh"
    plugins:
      - docker-compose#v2.6.0:
          run: arret

  - label: ":docker: Build (Rust Beta)"
    plugins:
      - docker-compose#v2.6.0:
          build: arret
          args:
            - rust_toolchain=beta
