cached-ecr-build-env: &cached-ecr-build-env
  plugins:
    - seek-oss/docker-ecr-cache#v1.5.0:
        target: build-env
        cache-on:
          - Cargo.lock
    - docker#v3.3.0

steps:
  - label: ":muscle: Test ARM64"
    branches: '!master'
    command: ./.buildkite/build-and-test.sh
    plugins:
      - docker-compose#v3.1.0:
          run: build-env
    agents:
      queue: arm64

  - label: ":fedora: LLVM Assert & Valgrind"
    branches: '!master'
    command:
      - "echo '--- :prettier: Checking rustfmt'"
      - cargo fmt -- --check

      - ./.buildkite/build-and-test.sh
      - ./.buildkite/valgrind-integration-tests.sh
    plugins:
      - seek-oss/docker-ecr-cache#v1.5.0:
          dockerfile: ./.buildkite/llvm-assert.Dockerfile
      - docker#v3.3.0

  - label: ":ubuntu: Test x86-64"
    command:
      - ./.buildkite/build-and-test.sh

      - "echo '--- :sleuth_or_spy: Checking release'"
      - RUSTFLAGS="-Copt-level=0" cargo check --release
    <<: *cached-ecr-build-env

  - wait

  - label: ":rust: Check (Rust Beta)"
    branches: "master"
    command:
      - "echo '--- :rust: Installing Rust beta'"
      - rustup default beta

      - "echo '--- :male-detective: Checking debug'"
      - cargo check

      - "echo '--- :female-detective: Checking release'"
      - RUSTFLAGS="-Copt-level=0" cargo check --release
      - cargo check --release
    <<: *cached-ecr-build-env

  - label: ":rocket: Push REPL Image"
    branches: "master"
    plugins:
      - docker-login#v2.0.1:
          username: etaoins
          password-env: DOCKER_HUB_PASSWORD
      - docker-compose#v3.1.0:
          push:
            repl:etaoins/arret:repl
          env:
            - BUILDKITE_COMMIT
    concurrency_group: 'push-repl-image'
    concurrency: 1

  - label: ":books: Update Rustdoc"
    branches: "master"
    command:
      # We need Nightly for intra-Rustdoc links. This is what crates.io uses as well.
      - "echo '--- :rust: Installing Rust nightly'"
      - rustup default nightly

      - "echo '--- :book: Building rustdoc'"
      - cargo doc --no-deps

      - "echo '--- :rust: Installing awscli'"
      - apt-get update
      - DEBIAN_FRONTEND=noninteractive apt-get -y install awscli

      - ./.buildkite/sync-rustdoc.sh
    <<: *cached-ecr-build-env
    concurrency_group: 'update-rustdoc'
    concurrency: 1
