steps:
  - label: ":docker: Build & Test"
    command:
      - /bin/bash -c "cargo build && cargo test && ./.buildkite/cross-i686.sh"
    plugins:
      - docker-compose#v2.6.0:
          run: full-compiler

  - label: ":docker: Build (Rust Beta)"
    plugins:
      - docker-compose#v2.6.0:
          build: full-compiler
          args:
            - rust_toolchain=beta

  - wait

  - label: ":docker: Push REPL Image"
    branches: "master"
    plugins:
      - docker-login#v2.0.1:
          username: etaoins
          password-env: DOCKER_HUB_PASSWORD
      - docker-compose#v2.6.0:
          push:
            repl:etaoins/arret:repl
          env:
            - BUILDKITE_COMMIT
