cached-ecr-build-env: &cached-ecr-build-env
  plugins:
    - seek-oss/docker-ecr-cache#v1.1.6:
        target: build-env
        cache-on:
          - Cargo.lock
    - docker#v3.0.1

steps:
  - label: ":ubuntu: Test x86-64"
    command:
      - ./.buildkite/build-and-test.sh

      - "echo '--- :sleuth_or_spy: Checking release'"
      - cargo check --release
    <<: *cached-ecr-build-env

  - label: ":muscle: Test ARM64"
    branches: '!master'
    command: ./.buildkite/build-and-test.sh
    plugins:
      - docker-compose#v3.0.1:
          run: build-env
    agents:
      queue: arm64

  - label: ":fedora: Test LLVM Assert & i686"
    branches: '!master'
    command:
      - ./.buildkite/build-and-test.sh

      - "echo '--- :prettier: Checking rustfmt'"
      - cargo fmt -- --check

      - ./.buildkite/cross-i686.sh
    plugins:
      - seek-oss/docker-ecr-cache#v1.1.6:
          dockerfile: ./.buildkite/llvm-assert.Dockerfile
      - docker#v3.0.1

  - wait

  - label: ":rust: Check (Rust Beta)"
    branches: "master"
    command:
      - "echo '--- :rust: Installing Rust beta'"
      - rustup default beta

      - "echo '--- :male-detective: Checking debug'"
      - cargo check

      - "echo '--- :female-detective: Checking release'"
      - cargo check --release
    <<: *cached-ecr-build-env

  - label: ":rocket: Push REPL Image"
    branches: "master"
    plugins:
      - docker-login#v2.0.1:
          username: etaoins
          password-env: DOCKER_HUB_PASSWORD
      - docker-compose#v3.0.0:
          push:
            repl:etaoins/arret:repl
          env:
            - BUILDKITE_COMMIT

