cached-ecr-build-env: &cached-ecr-build-env
  plugins:
    - seek-oss/docker-ecr-cache#v1.1.0:
        target: build-env
        cache-on:
          - Cargo.lock
    - docker#v2.0.0

push-repl-image-step: &push-repl-image-step
  branches: "master"
  plugins:
    - docker-login#v2.0.1:
        username: etaoins
        password-env: DOCKER_HUB_PASSWORD
    - docker-compose#v2.6.0:
        push:
          repl:etaoins/arret:repl
        env:
          - BUILDKITE_COMMIT

steps:
  - label: ":cargo: Build & Test"
    command:
      - cargo check --release
      - cargo build
      - cargo test
      - ./.buildkite/cross-i686.sh
      - ./driver/tests/integration/run.sh target/debug/arret
    <<: *cached-ecr-build-env

  - label: ":muscle: Test ARM64"
    command: bash -c "cargo build &&
                      cargo test &&
                      ./driver/tests/integration/run.sh target/debug/arret"
    plugins:
      - docker-compose#v2.6.0:
          run: build-env
    agents:
      queue: arm64

  - wait

  - label: ":rust: Build (Rust Beta)"
    branches: "master"
    command:
      - rustup default beta
      - cargo check
      - cargo check --release
    <<: *cached-ecr-build-env

  - label: ":rocket: Push x86-64 REPL Image"
    <<: *push-repl-image-step

  - label: ":rocket: Push ARM64 REPL Image"
    <<: *push-repl-image-step
    agents:
      queue: arm64
