steps:
  - label: ":cargo: Build & Test"
    command:
      - /bin/sh -c "cargo build &&
                    cargo test &&
                    ./.buildkite/cross-i686.sh &&
                    ./driver/tests/integration/run.sh target/debug/arret"
    plugins:
      - docker-compose#v2.6.0:
          run: full-compiler

  - wait

  - label: ":rocket: Push REPL Image"
    branches: "master"
    plugins:
      - docker-login#v2.0.1:
          username: etaoins
          password-env: DOCKER_HUB_PASSWORD
      - docker-compose#v2.6.0:
          push:
            repl:etaoins/arret:repl
          env:
            - BUILDKITE_COMMIT

  - label: ":rust: Build (Rust Beta)"
    branches: "master"
    plugins:
      - docker-compose#v2.6.0:
          build: full-compiler
          args:
            - rust_toolchain=beta
