[package]
name = "compiler"
version = "0.1.0"
edition = "2018"
authors = ["Ryan Cumming <etaoins@gmail.com>"]

[lib]
path = "lib.rs"
crate-type = ["lib"]

[dependencies]
llvm-sys = "60"
libc = "0.2"
ansi_term = "0.11"
libloading = "0.5"
syntax = { path = "../syntax" }
runtime = { path = "../runtime" }
runtime-syntax = { path = "../runtime-syntax" }

[dev-dependencies]
rayon = "1"
