[package]
name = "compiler"
version = "0.1.0"
authors = ["Ryan Cumming <etaoins@gmail.com>"]

[lib]
name = "compiler"
path = "lib.rs"
crate-type = ["lib"]

[dependencies]
ansi_term = "0.11"
libloading = "0.5"
syntax = { path = "../syntax" }
runtime = { path = "../runtime" }